version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (none for static site)"
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Build completed successfully"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/*
